kind: pipeline
type: docker
name: turborepo
steps:
  - name: build
    image: node:14.21-alpine
    commands:
      - pwd
      - npm install pnpm -g
      - pnpm i
      - npm run build
      - rm -rf /testweb/*
      - cp -r ./docs/.vitepress/dist /testweb
